// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/proto/properties.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Properties struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          map[string]*structpb.Value `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Properties) Reset() {
	*x = Properties{}
	mi := &file_internal_proto_properties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Properties) ProtoMessage() {}

func (x *Properties) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_properties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Properties.ProtoReflect.Descriptor instead.
func (*Properties) Descriptor() ([]byte, []int) {
	return file_internal_proto_properties_proto_rawDescGZIP(), []int{0}
}

func (x *Properties) GetData() map[string]*structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_proto_properties_proto protoreflect.FileDescriptor

const file_internal_proto_properties_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/properties.proto\x12\apathway\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x01\n" +
	"\n" +
	"Properties\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.pathway.Properties.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B-Z+github.com/npclaudiu/pathway/internal/protob\x06proto3"

var (
	file_internal_proto_properties_proto_rawDescOnce sync.Once
	file_internal_proto_properties_proto_rawDescData []byte
)

func file_internal_proto_properties_proto_rawDescGZIP() []byte {
	file_internal_proto_properties_proto_rawDescOnce.Do(func() {
		file_internal_proto_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_properties_proto_rawDesc), len(file_internal_proto_properties_proto_rawDesc)))
	})
	return file_internal_proto_properties_proto_rawDescData
}

var file_internal_proto_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_properties_proto_goTypes = []any{
	(*Properties)(nil),     // 0: pathway.Properties
	nil,                    // 1: pathway.Properties.DataEntry
	(*structpb.Value)(nil), // 2: google.protobuf.Value
}
var file_internal_proto_properties_proto_depIdxs = []int32{
	1, // 0: pathway.Properties.data:type_name -> pathway.Properties.DataEntry
	2, // 1: pathway.Properties.DataEntry.value:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_properties_proto_init() }
func file_internal_proto_properties_proto_init() {
	if File_internal_proto_properties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_properties_proto_rawDesc), len(file_internal_proto_properties_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_properties_proto_goTypes,
		DependencyIndexes: file_internal_proto_properties_proto_depIdxs,
		MessageInfos:      file_internal_proto_properties_proto_msgTypes,
	}.Build()
	File_internal_proto_properties_proto = out.File
	file_internal_proto_properties_proto_goTypes = nil
	file_internal_proto_properties_proto_depIdxs = nil
}
